common.o: common.c common.h
	gcc -c -g -Werror -Wall -o common.o $<

# test_open_file_from_arg: test_open_file_from_arg.c common.o
# 	gcc -g -o $@ common.o $<
#
# test: test_open_file_from_arg
# 	./test_open_file_from_arg.exe __common.h
#
# clean:
# 	rm -f *.exe
